### ISSUE TITLE
Add customData to play_media method

### ISSUE THREAD

**Issue by jhutchins** [home-assistant-libs/pychromecast#262]
It would be nice to be able to optionally add customData to the play request. I'm thinking to most straightforward option is to just add it as a defaulted parameter. Although it's could be added as a **kwargs parameter which I can't decide if that's a clever or crappy idea, but I'm leaning towards crappy.

**Comment by stefan-sherwood** [comment]
```play_media( url, 'audio/mpeg', metadata = { 'foo': 'my custom metadata', 'bar': 'is this what you're talking about?' } )```

**Comment by jhutchins** [comment]
No, there's a parameter in the load request object specifically called `customData`.

https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.messages.LoadRequestData#customData

**Comment by stefan-sherwood** [comment]
I guess it depends on _why_ you want to set the `customData`. When you include the `metadata` parameter as shown in my snippet that data is included in any notifications or queries of what is currently playing. You could probably use `metadata = { 'media_custom_data': 'your stuff' }` but I haven't tried that.

**Comment by stefan-sherwood** [comment]
IOW, the `metadata` parameter offers a superset of the functionality you're asking for.

**Comment by jhutchins** [comment]
It absolutely does not. For example, if you're trying to setup a custom MediaPlaybackInfoHandler[0] the parameters passed to your callback give you access to the `customData`, but not to the `metadata`. [1]

[0] https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.PlayerManager#setMediaPlaybackInfoHandler
[1] https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.messages.LoadRequestData

**Comment by stefan-sherwood** [comment]
I am using PyChromecast and not the Google APIs directly. I have two separate Python apps using PyChromecast, running on two different computers. One plays music and the other listens for media state changes. The one that receives the state changes gets the custom metadata fields that my player sets in the `play_media` command.

**Comment by jhutchins** [comment]
That's great I suppose for your use case, but that does not help in the case of adding custom authentication to a CAF application running on an actual Chromecast which is the canonical use case for the `customData` property.

**Comment by tibidi** [comment]
I added `customData` support here: https://github.com/home-assistant-libs/pychromecast/pull/585. I did validation with a French TV provider where we need to pass credentials in `customData`.
