### ISSUE TITLE
Casting shuffled PlayQueue from Plex to chromecast

### ISSUE THREAD

**Issue by rockstar2020** [home-assistant-libs/pychromecast#308]
Hi,
I have been able to successfully cast plex contents (movies, shows and playlists) to my chromecast ultra using pychromecast and plexapi components. 
But I'm not able to play shuffled playlist which is created via PlayQueue.
In other words, if I play playqueue as media my plex app on chromecast opens but nothing happens. 
Here is my command: cast.play_media(playq)
Also "playq" is basically a PlayQueue created from a playlist which can be played back with no issues. 
I know "playq" is properly created because I can print the titles using python command. 

Can somebody please help me out here with some hints or sample code?

Much appreciate it!

**Comment by Hellowlol** [comment]
Im not really sure what the issue is regarding the playqueue, but as a workaround you can pass a playlist to the play queue shuffle it send the play_media command then delete the playlist.
