### ISSUE TITLE
cast.set_volume sets volume to 100% for:  0 < volume <= 1

### ISSUE THREAD

**Issue by RadBrad87** [home-assistant-libs/pychromecast#373]
`level = 0.25`
`cast = pychromecast.Chromecast(ip) `
`cast.set_volume(float(level)) `
`mc = cast.media_controller`
`mc.play_media(media, 'video/mp4')`
`mc.block_until_active()`

From the log, it seems to be setting the correct (albeit coarsely rounded) value:
`2020-06-11 20:50:19,232 [INFO] Receiver:setting volume to 0.2`

But on the TV screen, I see the volume slider go to the top/max. 
The device I have is a Nvidia Shield TV with built in chromecast. 

I see the same behavior with this pychromecast based app I found:
https://pypi.org/project/chromecast-volumecontrol/0.0.6/#description

**Comment by emontnemery** [comment]
Can you set the volume with any other app or method, e.g. the official Google Home app?
If you can, try the `examples/simple_listener_example.py` script and check what the volume is set to, e.g.:
```
pychromecast_fork/examples$ python3 simple_listener_example.py --cast Lab
Listening for Chromecast events...
[ Sun Jun 14 09:53:56 2020  -  Lab ] status chromecast change:
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.4000000059604645, volume_muted=False, app_id='CC1AD845', display_name='Default Media Receiver', namespaces=['urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.broadcast', 'urn:x-cast:com.google.cast.media'], session_id='a192f13a-acc4-4b97-94a4-e57028d2d48e', transport_id='a192f13a-acc4-4b97-94a4-e57028d2d48e', status_text='Default Media Receiver', icon_url='')
[ Sun Jun 14 09:54:00 2020  -  Lab ] status chromecast change:
CastStatus(is_active_input=None, is_stand_by=None, volume_level=1.0, volume_muted=False, app_id='CC1AD845', display_name='Default Media Receiver', namespaces=['urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.broadcast', 'urn:x-cast:com.google.cast.media'], session_id='a192f13a-acc4-4b97-94a4-e57028d2d48e', transport_id='a192f13a-acc4-4b97-94a4-e57028d2d48e', status_text='Default Media Receiver', icon_url='')
```

**Comment by emontnemery** [comment]
Closing due to no update from OP
