### ISSUE TITLE
Is it possible to add casted track position

### ISSUE THREAD

**Issue by nikobix** [home-assistant-libs/pychromecast#374]
Hi, I have been using the pyChromecast for my Magic Mirror and all works fine.
I am looking to create a auto scrolling lyrics module but need to have an option for the current track/media position in time. 
I can see that we have the track/media length, which is usable, but to have an option to see exact position in a track would be very useful.
An addition to Pychromecast could be for lyrics, with auto scrolling.
Thanks

**Comment by emontnemery** [comment]
Yes, it's possible.

Please refer to the sample script `examples/simple_listener_example.py` for how to listen to events, you can use the sample script `examples/media_example2.py` at the same time for content that will generate `current_time`.

In-between the periodic events, you need to increase the `current_time` yourself when state is `PLAYING`.

**Comment by nikobix** [comment]
That's Great. I could see current time, but as it was not incrementing. I did not realise the current time only changed on a state change.
Thanks
