### ISSUE TITLE
Chromecast object has None host

### ISSUE THREAD

**Issue by tareco** [home-assistant-libs/pychromecast#381]
Hi,

I am getting always the value "None" for the host attribute of any Chromecast:

```py
import pychromecast
chromecasts = pychromecast.get_chromecasts()
for cc in chromecasts[0]:
  cc.wait()
  print(cc)
```

`Chromecast(None, port=8009, device=DeviceStatus(friendly_name...`

I am not sure if this is a bug or if I'm doing something wrong, but I can get lots of info from the CC including the current active App etc.. only the "host" never gives me an IP address.

Thank you.

**Comment by emontnemery** [comment]
It's not a bug, `pychromecast.get_chromecasts()` gets a list of chromecasts by using mDNS discovery, and will create Chromecast objects based on mDNS service data, not based on IP or host name.

Using IP or host name is strongly advised against as IP or host name may change over time, especially for audio groups where the group leader changes over time.

**Comment by tareco** [comment]
Ok, I understand. So this is now off-topic.. but how can I get the current IP address of the Chromecast? I am exploring the feasibility of configuring remotely some settings, such as the wifi network, and to POST data I'll need the IP. Thank you!

**Comment by emontnemery** [comment]
Sure, you can do like this:
https://github.com/home-assistant/core/blob/38210ebbc6a06220b3be3a29259e13683b693f4e/homeassistant/components/cast/discovery.py#L57-L81

```py
        # For support of deprecated IP based white listing
        zconf = ChromeCastZeroconf.get_zeroconf()
        service_info = None
        tries = 0
        while service_info is None and tries < 4:
            try:
                service_info = zconf.get_service_info(
                    "_googlecast._tcp.local.", service_name
                )
            except OSError:
                # If the zeroconf fails to receive the necessary data we abort
                # adding the service
                break
            tries += 1


        if not service_info:
            _LOGGER.warning(
                "setup_internal_discovery failed to get info for %s, %s",
                uuid,
                service_name,
            )
            return


        addresses = service_info.parsed_addresses()
        host = addresses[0] if addresses else service_info.server
```

**Comment by theychx** [comment]
@emontnemery 
> you can get the service_name from the chromecast object

Forgive my ignorance, but I can't seem to find it (the service_name).

PS:
Isn't [this](https://github.com/home-assistant-libs/pychromecast/blob/f3f8449d6edb3ec340f7172bd948cca20d52c697/pychromecast/__init__.py#L268) a mistake? Shouldn't it default to `None`?

**Comment by emontnemery** [comment]
> Forgive my ignorance, but I can't seem to find it (the service_name).
OK, so please have a look at https://github.com/home-assistant-libs/pychromecast/pull/385
It restores host+port in discovery data, and adds a new discovery helper `discover_listed_chromecasts`.
You should use that or `discover_chromecasts` instead of `get_chromecasts`.

Please refer to the newly added examples, `examples/discovery_example2.py` and `examples/discovery_example3.py`.
Note: Don't forget to close the returned browsers if you don't need discovery updates, because each call to the discovery helpers creates a new zeroconf instance but no longer closes it.

> Isn't this a mistake? Shouldn't it default to None?

Yes it is, thanks a lot!
