### ISSUE TITLE
Plex controller: no playback due to old version string

### ISSUE THREAD

**Issue by davyhollevoet** [home-assistant-libs/pychromecast#384]
The Plex controller `media_to_chromecast_command` payload contains an old version string (from early 2017, as per https://www.videohelp.com/software/Plex/old-versions)
https://github.com/home-assistant-libs/pychromecast/blob/85c352f84d77f80a6dc1ff47057e3535b4f1aa8f/pychromecast/controllers/plex.py#L129

When sending that to Plex 1.18+<sup>1</sup>, the media loads, buffers and shows the metadata, but it doesn't play, going to a full gray screen instead. When the version string is changed to "1.10.1.4602"<sup>2</sup> (late 2017, still ancient), playback works again.

I'm guessing that the version should actually match the server version. PlexApiController might do that by making an API call, but PlexController can only be mended by updating the version and breaking it out as a parameter to allow overriding it.

```diff
diff --git a/pychromecast/controllers/plex.py b/pychromecast/controllers/plex.py
index 163fd15..0faf286 100644
--- a/pychromecast/controllers/plex.py
+++ b/pychromecast/controllers/plex.py
@@ -53,6 +53,7 @@ def media_to_chromecast_command(
     autoplay=True,
     currentTime=0,
     playQueueID=None,
+    version="1.10.1.4602",
     **kwargs
 ):  # noqa: 501 pylint: disable=invalid-name, too-many-arguments, too-many-locals, protected-access, redefined-builtin
     """Create the message that chromecast requires. Use pass of plexapi media object or
@@ -80,6 +81,7 @@ def media_to_chromecast_command(
         username (None): user name of the person that start the playback.
         autoplay (bool): Auto play after the video is done.
         currentTime (int): Set playback from this time. default 0
+        version (str): pms version. Default 1.10.1.4602
         **kwargs: To allow overrides, this will be merged with the rest of the msg.
 
     Returns:
@@ -126,7 +128,7 @@ def media_to_chromecast_command(
                     "transcoderVideo": transcoderVideo,
                     "transcoderVideoRemuxOnly": transcoderVideoRemuxOnly,
                     "transcoderAudio": transcoderAudio,
-                    "version": "1.4.3.3433",
+                    "version": version,
                     "myPlexSubscription": myPlexSubscription,
                     "isVerifiedHostname": isVerifiedHostname,
                     "protocol": protocol,
```

[1] I noticed this problem first after upgrading my Plex in 2019/11; PMS 1.18 appeared a bit earlier. Not sure which version I upgraded to then. I was using a custom controller at the time.
[2] I didn't try other, earlier versions. There seems little point in doing so? I'm not sure where I got it, perhaps from https://github.com/d8ahazard/Cast.bundle/blob/4f97e1b1c3437a4b0cda4a4119aae15c486e8b9d/Contents/Libraries/Shared/pychromecast/controllers/plex.py#L141 ?

**Comment by Codisimus** [comment]
Was trying to get this to work. Used d8ahazards custom `plex.py` (among others) which did not help.

Was about to submit an issue myself but had no idea what the cause was.

Updating that version in `pychromecast` did the trick. Thank you!

**Comment by emontnemery** [comment]
Please open a PR with this change!
