### ISSUE TITLE
Mild documentation change

### ISSUE THREAD

**Issue by borland502** [home-assistant-libs/pychromecast#388]
Hey, thanks for all the hard work you put into this.  One thing that took a novice like me a bit to get past is a change in the response of this example line:

`cast = next(cc for cc in chromecasts if cc.device.friendly_name == "Living Room")`

The chromecasts object now contains an additional object

`<ServiceBrowser(zeroconf-ServiceBrowser__googlecast._tcp.local._123145484107776, started daemon 123145484107776)>)"`

I got around it by referencing the first element, but there may be a more elegant way I'm not seeing at the moment.

`cast = next(cc for cc in chromecasts[0] if cc.device.friendly_name == "Living Room")`

**Comment by emontnemery** [comment]
OK, the documentation needs to be updated.
Please have a look at the examples, they are updated.

**Comment by borland502** [comment]
Works for me, thank you.  That is better than what I did.  I'm still attaining proficiency with python syntax
