### ISSUE TITLE
Spotify example: requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by Esamanoaz** [home-assistant-libs/pychromecast#393]
Using the Spotify example, I keep getting this error when the program runs this code:
`data = st.start_session('args.user', 'args.password')`
Which results in this error:
`requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`
My Spotify password is correct (I double checked) and I have a premium subscription, so I don't know why it would do this.

I am trying to play music on my Google Home Mini. Does pychromecast and the Spotify Controller only work with Chromecast devices? I can connect to the Google Home Mini and print out `print(cast.status)` or `print(cast.device)`, so I don't understand why this would be an issue.

Any ideas?

[Full code](https://pastebin.com/fGguFu3t) or paste this into a browser: https://pastebin.com/fGguFu3t

EDIT: I tried playing music through Spotify on my Chromecast instead of my Google Home Mini but it had the same result. `requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`

**Comment by Esamanoaz** [comment]
I ran the file with `--show-debug` as an arg and [this is what was displayed](https://pastebin.com/2y0jk6CV) when it hit line 45 of my code

Or paste this into a browser: https://pastebin.com/2y0jk6CV

**Comment by Esamanoaz** [comment]
I fixed this issue by following the usage guide at https://github.com/enriquegh/spotify-webplayer-token

**Comment by emontnemery** [comment]
@Esamanoaz OK, does the spotify example script need to be updated accordingly?

**Comment by Esamanoaz** [comment]
@emontnemery Yes, I think it should be changed. In the Spotify example, the values passed in where cookies should be passed in are called `args.user` and `args.password`. This lead me to believe that I just needed to input my Spotify username and password, which isn't true. Maybe add a link in a comment to the spotify-token github repo.
