### ISSUE TITLE
get_chromecasts() backwards incompatible change

### ISSUE THREAD

**Issue by keredson** [home-assistant-libs/pychromecast#398]
Hello,

Previously `get_chromecasts(blocking=True)` returned a list of chromecast devices.  Now it returns a tuple of that list and a `browser` object.  `return (cc_list, browser)`

The docstring still describes the old behavior: 

`:param blocking: If True, returns a list of discovered chromecast devices.`

Change was here (13 days ago):
https://github.com/home-assistant-libs/pychromecast/commit/e8d04cd9a12b4f434f69a98f2eb03d44fbc302ae#diff-cd08193135e2ec94e86f3678d2bfdddfR207

Is this intended new behavior?

Derek

**Comment by keredson** [comment]
Gentle ping.  I'll be happy to code up a PR if one of these possible fixes are ACKed:
- create a different method `get_chromecasts_with_browser()`
- add a `with_browser=False` param

**Comment by emontnemery** [comment]
The change is intended, but a `with_browser=False` option would be OK

**Comment by balloob** [comment]
We did a major version bump and marked it as a breaking change.

I think that we should fix the docstring and then that's it. If you just want the Chromecasts, you can call `get_chromecasts(blocking=True)[0]`

**Comment by emontnemery** [comment]
The docstrings have already been fixed. The service browser starts several threads so it should be stopped, just doing `get_chromecasts(blocking=True)[0]` is not good.

**Comment by emontnemery** [comment]
@keredson Can you explain in which use case it is not useful to get the browser object?

**Comment by emontnemery** [comment]
Closing because the question has been answered (the backwards incompatible change was intentional)
