### ISSUE TITLE
Spotify `setCredentials` call and `expiresIn` field

### ISSUE THREAD

**Issue by MagicMicky** [home-assistant-libs/pychromecast#407]
In the Spotify controller you send a `setCredentials` request to the Spotify App on the chromecast, to log in the user [link](https://github.com/home-assistant-libs/pychromecast/blob/master/pychromecast/controllers/spotify.py#L71-L77).

This call contains an `expiresIn` field, that I suppose should contain the `expiresIn` field returned when generated an access token (which is 1h). 

What happens after this `expiresIn` expires is that the Chromecast playback completely stops.

I'm trying to investigate how this expiresIn could be postpone (ie: updating the token used and the `expiresIn`), but am having trouble on finding details of the API used to communicate with the Spotify App on chromecast.

Am I correct that this `setCredentials` call is part of the Spotify App API on Chromecast? Is there any documentation regarding this call? How did you find out about it?

FYI I've detailed in https://github.com/fondberg/spotcast/issues/13#issuecomment-680189631 my approach to investigate these APIs (using wireshark) but because of protobuff, I am facing trouble using wireshark or similar to intercept the traffic between ie: pychromecast and the chromecast, or spotify desktop app and chromecast when casting.

**Comment by fondberg** [comment]
The data in the message is vendor specific to my knowledge and therefor one would have to sniff the traffic.

**Comment by emontnemery** [comment]
Please reopen if there is progress in fondberg/spotcast#13
