### ISSUE TITLE
When to call stop_discovery?

### ISSUE THREAD

**Issue by dominikkarall** [home-assistant-libs/pychromecast#408]
Hi,

I have an issue that from time to time my cast devices are discovered several times in a few days. I'm using the non blocking `get_chromecasts` function to discover my cast devices and keep the connection to the devices active until the program stops (so actually never).
I call `stop_discovery` at the very end of the program when it shuts down so that never happens and therefore discovery is continuing. I thought, that further updates from the same device are handled with the `update_callback` instead of `add_callback`, but actually they are calling the `add_callback` and so a lot of "new" devices get discovered after some days due to connection issues or nightly reboots.

Can you please explain if `stop_discovery` should be called just after the cast device was discovered? If so, what happens if the device is offline for a few days and is connected to the network with a new IP address? Would it be properly updated? I thought that that's something what `update_callback` is doing and therefore I didn't stopped the discovery.

Thanks for explanation!

**Comment by emontnemery** [comment]
@dominikkarall You should call `stop_discovery` at the very end of the program just like you're doing.
There are two reasons to keep discovery running:
- Discover new chrome cast devices
- Discover updates for a known chromecast, the service name may change, or group leadership may be passed around in case of audio groups.

I'm not fully sure what you mean by `add_callback` and `update_callback`, maybe you can share a code snippet explaining what you're doing?

**Comment by dominikkarall** [comment]
Here is my current code
```
def startDiscovery(self):
        def castFound(chromecast):
            if chromecast.name == self.hash["CASTNAME"]:
                logger.info("=> Discovered cast: " + chromecast.name)
                # FIXME do I need to disconnect here? Otherwise I would have 2 chromecasts
                # with listeners and therefore receive 2 events instead of 1 on the listeners
                if self.cast:
                    # disconnect existing cast device if there is any
                    self.cast.disconnect(blocking=False)
                self.cast = chromecast
                # add status listener
                self.cast.register_connection_listener(self)
                self.cast.register_status_listener(self)
                # add media controller listener
                self.cast.media_controller.register_status_listener(self)
                # timeout 0.001 just waits for status to be ready
                # but we just need the thread to start by calling wait()
                self.cast.wait(0.001)

        logger.debug("Start discovery")
        self.browser = pychromecast.get_chromecasts(blocking=False, tries=None, retry_wait=5, timeout=5, callback=castFound)
```

I assume that I need to have this disconnect in place, otherwise it happens that the last connected cast device reconnects and I receive the castFound callback as well.

**Comment by emontnemery** [comment]
If you're waiting for a specific named chromecast, `pychromecast.get_chromecasts` is not really ideal as it creates Chromecast instances for each discovered Chromecast.
However it should work, and there should not be duplicated Chromecasts. This is a bug in `get_chromecasts` where it incorrectly creates a new Chromecast instance each time an mDNS service is added instead of each time a previously unknown UUID is found.
Would you mind testing the attempted correction in #411?

> I thought also about changing the if statement to
>```
>if chromecast.name == self.hash["CASTNAME"] and self.cast is None:
>```
>to run the code only once, but would that allow all updates via zeroconf, even if the device was removed for a few days and reconnected with a different IP?
Sure, that's the intention.

Note:
Please beware that the Chromecast's name is not unique, it's fully possible to give several or all Chromecasts the same name.
Uniqueness is based on UUID (chromecast.uuid).

**Comment by dominikkarall** [comment]
Thanks for the fix. I just installed it and will keep it running over night. I'll let you know if it works.

**Comment by dominikkarall** [comment]
It seems that the fix is working, no more duplicates, thanks!
