### ISSUE TITLE
Disconnect doest work for few apps while pychromecast is runing.

### ISSUE THREAD

**Issue by karthikpanicker** [home-assistant-libs/pychromecast#419]
I use status listener to keep track of Chromecast status. Chromecasts are discovered in a non blocking call and status listener registered post a successful call to wait method on the chromecast instance. While pychromecast is running few apps like soundcloud, bbc iplayer, All 4, My 5 functions normally except for the 'Stop Casting' functionality. Chromecast doesn't stop the application when the 'Stop Casting' button is pressed in the app. The moment pychromecast is stopped, 'Stop casting' works normally. This issues is not seen in youtube, netflix, amazon prime etc.

**Comment by emontnemery** [comment]
@karthikpanicker did you solve your problem?
