### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by czikus** [home-assistant-libs/pychromecast#425]
Python 3.9 removed the deprecated `threading.Thread.isAlive` which is now replaced by `threading.Thread.is_alive`. This leads to the following error:

```
 File "pychromecast/__init__.py", line 489, in wait
    if not self.socket_client.isAlive():
AttributeError: 'SocketClient' object has no attribute 'isAlive'
```

Even Python 2 includes the new spelling, so it should be an easy fix.

**Comment by emontnemery** [comment]
Thanks @czikus!
