### ISSUE TITLE
Potentially stupid question..

### ISSUE THREAD

**Issue by strunker** [home-assistant-libs/pychromecast#434]
Recently got a vizio tv with chromecast embedded. Have been using pychromecast to send audio to speakers of my choice for a while but the TV changes things a bit.

What I am wanting to know is if there is anyway to know if the TV is "on" or "off". I dont think so because the chromecast kind of sits outside the normal TV functions but wanted to ask. I think the closest I can maybe get to this is "is_active_input" to understand whether or not the chromecast is in use. But if I have some other streamer plugged in and the CC is not the active input I imagine this method would not work?

Simply trying to be able to query the TV to understand its power state is all. 

Thanks

**Comment by emontnemery** [comment]
This is not supported.
You're in better luck looking for a library or tool which can control vizio TVs
