### ISSUE TITLE
Unable to send local stream to Google Home Mini

### ISSUE THREAD

**Issue by ganralf75** [home-assistant-libs/pychromecast#445]
Hello,

I have tried to send a locally created .mp3 file through a local webserver to my google home device with no success.

mc.play_media(r'localhost:8000/helloworld.mp3', 'audio/mpeg')

If I copy the destination url to the .mp3 file to a browser it is played without any problem. So there seems to be no problem w/ the web-server in general.

I also tried to send a generic mp3 file from the internet to my google home device using the play_media() method and it is played w/o any problem.

What am I doing wrong?

thanks for any advice!

best regards,
ganralf75

**Comment by ssieb** [comment]
"localhost" is only valid on your computer.  You need to use the IP address instead.

**Comment by elibroftw** [comment]
You can look at how my music player does it. Basically you get the ipv4 or ipv6 of your computer and send that up address to the Google home mini. You also need a web framework to handle the request + make sure conditional sending is on in order to scrub properly.

**Comment by emontnemery** [comment]
Thanks @ssieb and @elibroftw 👍
