### ISSUE TITLE
DeprecationWarnings related to Protobuf on Python 3.9

### ISSUE THREAD

**Issue by sprt** [home-assistant-libs/pychromecast#447]
Starting with Python 3.9, running the test suite of my program that uses pychromecast yields a bunch of `DeprecatingWarnings` seemingly related to Protobuf. Please see below for the full log.

<details><summary>Log</summary>
<pre>
.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:19
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:19: DeprecationWarning: Call to deprecated create function FileDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    DESCRIPTOR = _descriptor.FileDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:33
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:33: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:37
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:37: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:41
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:41: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:27
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:27: DeprecationWarning: Call to deprecated create function EnumDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _SIGNATUREALGORITHM = _descriptor.EnumDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:60
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:60: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:64
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:64: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:54
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:54: DeprecationWarning: Call to deprecated create function EnumDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _HASHALGORITHM = _descriptor.EnumDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:90
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:90: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:84
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:84: DeprecationWarning: Call to deprecated create function EnumDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _CASTMESSAGE_PROTOCOLVERSION = _descriptor.EnumDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:108
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:108: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:112
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:112: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:102
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:102: DeprecationWarning: Call to deprecated create function EnumDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _CASTMESSAGE_PAYLOADTYPE = _descriptor.EnumDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:130
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:130: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:134
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:134: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:138
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:138: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:124
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:124: DeprecationWarning: Call to deprecated create function EnumDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _AUTHERROR_ERRORTYPE = _descriptor.EnumDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:158
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:158: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:165
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:165: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:172
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:172: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:179
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:179: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:186
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:186: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:193
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:193: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:200
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:200: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:151
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:151: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _CASTMESSAGE = _descriptor.Descriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:233
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:233: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:240
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:240: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:247
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:247: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:226
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:226: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _AUTHCHALLENGE = _descriptor.Descriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:278
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:278: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:285
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:285: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:292
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:292: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:299
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:299: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:306
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:306: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:313
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:313: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:320
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:320: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:271
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:271: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _AUTHRESPONSE = _descriptor.Descriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:351
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:351: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:344
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:344: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _AUTHERROR = _descriptor.Descriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:383
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:383: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:390
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:390: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:397
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:397: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:376
  /home/xxxxx/yyyyy/.tox/py39/lib/python3.9/site-packages/pychromecast/cast_channel_pb2.py:376: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _DEVICEAUTHMESSAGE = _descriptor.Descriptor(
</pre>
</details>

**Comment by emontnemery** [comment]
I don't think this is an issue in pychromecast: https://github.com/protocolbuffers/protobuf/issues/7978
