### ISSUE TITLE
[Discussion] Adding "keep alive" support, to avoid the initial cast sound

### ISSUE THREAD

**Issue by CarlosGS** [home-assistant-libs/pychromecast#463]
Keeping the chromecast/home alive prevents the initial "WHOOMPH" sound. This is very convenient.

It only seems possible to achieve this by periodically sending an audio:

- https://community.home-assistant.io/t/i-did-it-i-defeated-the-horrible-google-home-cast-start-prompt-sound/36123
- 2021 version of the YAML: https://community.home-assistant.io/t/i-did-it-i-defeated-the-horrible-google-home-cast-start-prompt-sound/36123/61
- https://community.home-assistant.io/t/text-to-speech-problem-with-chromecast-audio/65304

The original author's approach of periodically running the `turn_on` command sounds more clean. The command has been fixed since, as it doesn't toggle ON and OFF anymore,
but it fails at keeping the chromecast alive. Only the silent audio method works.

However, this method has an evident issue:
![Screenshot_20210217_121300](https://user-images.githubusercontent.com/1636266/108196528-7ec6a200-7119-11eb-8aee-4182b88ee139.png)

What are your thoughts? Would it be possible to integrate this in a more transparent manner?
Cheers!

**Comment by emontnemery** [comment]
@CarlosGS What kind of chromecast device is this? There shouldn't be any sound generated by pychromecast connecting to a chromecast, there may however be a sound when an app is started.
You're using Home Assistant, are you starting the Home Assistant Cast app?

**Comment by emontnemery** [comment]
One more thing: The Google Home app has a setting "Playback sounds" which should prevent the noise, doesn't that work for you?

**Comment by emontnemery** [comment]
The noise is heard every time an app is launched on the cast device, and the chromecast will shut down an idle app after a few minutes.

Hence, playing a silent mp3 keep the chromecast from killing the app but it may make the problem even worse if the chromecast doesn't have a stable network connection as reported in home-assistant/core#47923

I have no good idea for fixing this TBH.

**Comment by CarlosGS** [comment]
Yep, I don't see the option, at least for Google Home Mini.

Best solution would be for Google to either disable the sound or to provide the option. If it is already available in Chromecast Audio, that'd be a good start. But then again Google isn't that known for hearing user's suggestions :S

It seems https://github.com/home-assistant/core/issues/47923 is a separate bug (`[pychromecast.socket_client] Heartbeat timeout, resetting connection`) that has the effect of breaking the silent audio method. But once that is fixed, the silent audio method should be robust again. Though I hope someone can find a more elegant "keep alive" solution.

**Comment by CarlosGS** [comment]
The library supports manufacturer's specification, and it doesn't make sense to patch this behavior from within.

Also, the HASS automation was made more robust upon WiFi disconnections by incorporating the unavailable state ([link](https://community.home-assistant.io/t/i-did-it-i-defeated-the-horrible-google-home-cast-start-prompt-sound/36123/61)).
