### ISSUE TITLE
JSON Data Exchange - New App

### ISSUE THREAD

**Issue by blawford** [home-assistant-libs/pychromecast#499]
I have been looking at adding a new application controller.

Looking at the instructions https://github.com/home-assistant-libs/pychromecast#exploring-existing-namespaces makes sense, so I attempted it against a stream on an existing integration (supla.fi) to see how it correlated to the controller implementation before attempting my own.

Trouble is, I'm not seeing anything in the net-export file (https://pastebin.com/9HySUCJC) following the instructions that correlates to anything I am seeing in code. I was expecting to see something captured that related to the properties in the msg variable in the controller play_media method?

    def play_media(self, media_id, is_live=False):
        """
        Play Supla media
        """
        msg = {
            "type": "load",
            "mediaId": media_id,
            "currentTime": 0,
            "isLive": is_live,
            "isAtLiveMoment": False,
            "bookToken": "",
            "sample": True,
            "fw_site": "Supla",
            "Sanoma_adkv": "",
            "prerollAdsPlayed": True,
            "supla": True,
            "nextInSequenceList": 0,
            "playbackRate": 1,
            "env": "prod",
        }
        self.send_message(msg, inc_session_id=True)

Can someone point me in the right direction or tell me what I am doing wrong?

**Comment by balloob** [comment]
Those instructions are really old and probably no longer correct.

**Comment by blawford** [comment]
> Those instructions are really old and probably no longer correct.

Yeah, I did think as much from the mention of the Google Cast Chrome extension, which hasn't existed for a while.

Any idea of a workable way now?

**Comment by emontnemery** [comment]
The method outlined here https://github.com/home-assistant-libs/pychromecast#exploring-existing-namespaces will log what is sent and works just fine to capture how a supla stream is played for example.

After you capture the log, you need to walk through the different connections until you find the one which is the connection with the chromecast you streamed to, see an example below.

However: This ONLY works for services which support casting through Google Chrome.
Some services will revert to "cast tab", which just does screen mirroring.

In such cases you need to intercept the traffic between an Android phone and the chromecast to find the message scheme for the chromecast app.

One way is to use Frida as outlined here: https://github.com/home-assistant-libs/pychromecast/issues/432#issuecomment-798474599, but i have only been able to dump messages received from the device so it might not be helpful in you case.

```
t=162384 [st=63415196]  SSL_SOCKET_BYTES_SENT
                        --> byte_count = 410
                        --> bytes =
                          00 00 01 96 08 00 12 12  31 36 32 30 33 32 37 37     ... ..16203277
                          32 39 39 38 36 37 37 37  32 36 1A 24 37 63 63 33   2998677726.$7cc3
                          39 38 39 39 2D 64 61 34  33 2D 34 64 32 61 2D 38   9899-da43-4d2a-8
                          64 31 65 2D 38 62 63 61  36 34 62 31 32 64 66 65   d1e-8bca64b12dfe
                          22 1E 75 72 6E 3A 78 2D  63 61 73 74 3A 66 69 2E   ".urn:x-cast:fi.
                          72 75 75 74 75 2E 63 68  72 6F 6D 65 63 61 73 74   ruutu.chromecast
                          28 00 32 B5 02 7B 22 53  61 6E 6F 6D 61 5F 61 64   ( 2..{"Sanoma_ad
                          6B 76 22 3A 22 22 2C 22  63 75 72 72 65 6E 74 54   kv":"","currentT
                          69 6D 65 22 3A 31 36 2E  36 38 2C 22 65 6E 76 22   ime":16.68,"env"
                          3A 22 70 72 6F 64 22 2C  22 66 77 5F 73 69 74 65   :"prod","fw_site
                          22 3A 22 53 75 70 6C 61  22 2C 22 69 73 41 74 4C   ":"Supla","isAtL
                          69 76 65 4D 6F 6D 65 6E  74 22 3A 66 61 6C 73 65   iveMoment":false
                          2C 22 69 73 4C 69 76 65  22 3A 66 61 6C 73 65 2C   ,"isLive":false,
                          22 6D 65 64 69 61 49 64  22 3A 22 64 38 31 36 65   "mediaId":"d816e
                          66 39 64 2D 61 62 33 61  2D 34 61 35 34 2D 61 34   f9d-ab3a-4a54-a4
                          35 33 2D 62 36 66 31 64  62 33 61 36 64 36 66 22   53-b6f1db3a6d6f"
                          2C 22 6D 65 64 69 61 54  79 70 65 22 3A 22 62 6F   ,"mediaType":"bo
                          6F 6B 22 2C 22 6E 65 78  74 49 6E 53 65 71 75 65   ok","nextInSeque
                          6E 63 65 4C 69 73 74 22  3A 66 61 6C 73 65 2C 22   nceList":false,"
                          70 6C 61 79 62 61 63 6B  52 61 74 65 22 3A 31 2C   playbackRate":1,
                          22 70 6F 73 74 72 6F 6C  6C 4D 65 64 69 61 22 3A   "postrollMedia":
                          33 35 32 34 37 33 38 2C  22 70 72 65 72 6F 6C 6C   3524738,"preroll
                          41 64 73 50 6C 61 79 65  64 22 3A 66 61 6C 73 65   AdsPlayed":false
                          2C 22 73 61 6D 70 6C 65  22 3A 74 72 75 65 2C 22   ,"sample":true,"
                          73 75 70 6C 61 22 3A 74  72 75 65 2C 22 74 79 70   supla":true,"typ
                          65 22 3A 22 6C 6F 61 64  22 7D                     e":"load"}
```

**Comment by blawford** [comment]
Thanks for the reply @emontnemery - I have re-run the logging and found what you have referenced.

Thanks for the additional information, the fall-back to casting the tab does seem to be true of the service I am trying to get the integration for so I will have a look at the Android option next.

**Comment by blawford** [comment]
Okay, got Frida up and running on an Android emulator. 

What do I put in __handlers__\libc.so\open.js in order for it to log the information I need?

**Comment by emontnemery** [comment]
Nothing I think?

IIRC I just used `frida-trace -U -p <port> -j '*!*qdk.write*/i' -o dump.txt`, I don't think it requires anything more than the frida-server running on the phone.
Does that not work? You are rooted, right?

There's also this, https://github.com/google/ssl_logger, which I should admit I have not tried.

**Comment by blawford** [comment]
Yes, I have root on the emulator. 

I am going to go for a complete rundown of what I did, as a C# developer I haven't touched python or android before, so I could easily have mis-stepped somewhere.

If I run the command you mentioned `frida-trace -U -p 17681 -j '*!*qdk.write*/i' -o dump.txt` I get the following message:
`Started tracing _0_ functions. Press Ctrl+C to stop.` and I get an empty output file.

From some googling I have tried the following command `frida-trace -U -i open com.bbc.sounds -j '*!*qdk.write*/i' -o dump.txt` which gives the following output:

    Instrumenting...
    open: Auto-generated handler at         
    "C:\\Users\\ben\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\__handlers__\\libc.so\\open.js"
    Started tracing 1 function. Press Ctrl+C to stop.

by default gives me lots of lines in the file all saying `open()` and nothing else. This is due to the aforementioned open.js just containing the following:

    {
      /**
       * Called synchronously when about to call open.
       *
       * @this {object} - Object allowing you to store state for use in onLeave.
       * @param {function} log - Call this function with a string to be presented to the user.
       * @param {array} args - Function arguments represented as an array of NativePointer objects.
       * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
       * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
       * @param {object} state - Object allowing you to keep state across function calls.
       * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
       * However, do not use this to store function arguments across onEnter/onLeave, but instead
       * use "this" which is an object for keeping state local to an invocation.
       */
      onEnter(log, args, state) {
        log('open()');
      },
    
      /**
       * Called synchronously when about to return from open.
       *
       * See onEnter for details.
       *
       * @this {object} - Object allowing you to access state stored in onEnter.
       * @param {function} log - Call this function with a string to be presented to the user.
       * @param {NativePointer} retval - Return value represented as a NativePointer object.
       * @param {object} state - Object allowing you to keep state across function calls.
       */
      onLeave(log, retval, state) {
      }
    }

So I guess to get something useful into the logging, I need to change that file... Or I could be completely off track!

**Comment by blawford** [comment]
Now I read my message again it occurs to me that the parameter open in my command is why I am probably down this avenue and it doesn't line up with your experience. That probably should have been obvious!

**Comment by blawford** [comment]
So I am a bit stuck, I understand a bit better what I have been doing wrong but still don't know what to do next.

I have realised that 'open' keyword leaves me looking at calls within the base C++ library, which probably isn't what I want. 

Letting it list all the libraries within the application did show it using 'libprotobuf_cpp_lite.so', which from what I understand might be on the right lines? But I am struggling to get any output by limiting it to this library. 

@emontnemery I had a look at the SSL logger link but didn't fully how to run it (wasn't sure what how to connect it to the emulators process and when I tried to run it I got a syntax error around a print statement on line 343).

Any ideas of what I am doing wrong. Sorry for my inexperience here, I am probably doing something obviously incorrect.

**Comment by blawford** [comment]
Never did figure out what I was doing wrong with Frida. I did start on another app by the same provider that did allow casting from chrome desktop and this gave me enough to guess my way to the original app I was trying to integrate.

Hopefully will have something in the near future.
