### ISSUE TITLE
How to specify application to play media

### ISSUE THREAD

**Issue by lexxstorm** [home-assistant-libs/pychromecast#508]
I want to play_media through MX Player instead of default player. I ve found that some links i am trying to play 'video/mp4' have a codec which didnt played at the default player and excellent played in MX Player. So how to specify the application for playing video files. (or get APP_ID for MX Player)

mc = cast.media_controller
mc.play_media(video_link, "video/mp4")

**Comment by emontnemery** [comment]
You need to implement a controller for the MX player, 
If the MX Player itself implements the media API specified by Google and doesn't have any advanced features, the implementation is very simple, please see `pychromecast/controllers/bubbleupnp.py` for an example.

If the MX player's cast app is open source, it should be very straight forward.

A PR adding this support would be most welcome 👍
