### ISSUE TITLE
Youtube Music app not supported

### ISSUE THREAD

**Issue by jemershaw** [home-assistant-libs/pychromecast#523]
I was trying to cast "Youtube Music" app via the cast plugin but I keep getting the error message that `2021-08-23 02:16:22 ERROR (SyncWorker_1) [homeassistant.components.cast.media_player] App Youtube Music not supported`. Is this something someone could add?

**Comment by emontnemery** [comment]
I'm closing this due to no response.
@jemershaw please open a new issue if this is still a problem 👍
