### ISSUE TITLE
9.3.0 - get_chromecasts() bug 

### ISSUE THREAD

**Issue by strunker** [home-assistant-libs/pychromecast#550]
I was using 9.2.1 previously, the latest release prior to 9.3.0, everything was great.

Below is an image of the discovery done on 9.2.1, you can see 7 unique devices.

![image](https://user-images.githubusercontent.com/6154660/137903908-d6dde1a1-f3d9-46dd-b6de-6e97cc7d414f.png)

When moving to 9.3.0 and running the exact same code, we only get 4 devices ( see image below) and of those 4, 2 of them are duplicates, so it really only found 3 of them. Its also FAR slower than 9.2.1 is at discovering. Takes roughly 4-5x longer to return results, and the result it returns are incorrect. 

Needless to say, I will be returning to 9.2.1 for the time being.

![image](https://user-images.githubusercontent.com/6154660/137904133-b4a8ff32-2308-4933-b6d9-e6278ea8a2f1.png)

**Comment by strunker** [comment]
> Thanks, can you try the changes in #551?
> 
> Note that the `get_chromecasts()` function is probably not what you want, it does a once-off blocking discovery, and connects to all discovered chromecasts.
> 
> Check out the `examples/discovery_example.py`, it shows how to dynamically keep track of devices as they appear or disappear from the network.

I actually offload the discovery to a thread, so non blocking in that sense, but I will review that example. I havent touched the code for this in a while so perhaps better, more async, methods have been added since then.  I will try #551 out.

**Comment by emontnemery** [comment]
Thanks a lot for testing!
