### ISSUE TITLE
How to cast to a custom receiver?

### ISSUE THREAD

**Issue by esbenvb** [home-assistant-libs/pychromecast#565]
I have made a chrome cast app and registered my CC for development, in the Google Cast developer console, and now I want to cast the ID of my app to my own Chromecast, using pychromecast.

My cast app is a custom receiver, which points to a URL online. 

However, I don't see any examples or documentation that can help me out. I also tried searching for "custom receiver" here, without any reuslts.

How do I solve this?

**Comment by alexdebiasio** [comment]
Just launch your receiver using:
`chromecast.start_app(YOUR_APP_ID)`

**Comment by esbenvb** [comment]
Thank you, it seems to work - is this function (which is pretty essential) documented anywhere? :)

**Comment by alexdebiasio** [comment]
It's briefly documented on the code, check the Chromecast class for other useful functions.
