### ISSUE TITLE
What is exactly dashcast ?

### ISSUE THREAD

**Issue by Sebwap** [home-assistant-libs/pychromecast#567]
Hello,

I saw in examples sections that we can "cast" an url with dashcast controller.
But can I cast any url, or does it need some specific code on the "server" part ?

My goal is to have a specific, light, web page to display on my Nest Hub, with relevants informations.

**Comment by emontnemery** [comment]
It should be this one: https://github.com/stestagg/dashcast

It's not been updated for a while though, I'd expect it to not work well on Google Nest hubs running Fuchsia OS.

**Comment by Sebwap** [comment]
Well it seem to work for some website :)
I will try to see how to make a compatible website !

Thx for your reply :)
