### ISSUE TITLE
Support initial out-of-box Chromecast setup

### ISSUE THREAD

**Issue by interfect** [home-assistant-libs/pychromecast#572]
If I have a new or freshly factory-reset Chromecast, I would like to be able to use pychromecast to do the initial configuration of the device and tell it what wifi network to connect to.

Currently, the only Google-supported method to do the out-of-box or post-reset setup is to go out and additionally purchase an iOS device, or an Android device with the Google Play Store and Google Play Services pre-installed, and to use that to install an app called "Google Home", and then to use that to configure the wifi settings.

**Comment by emontnemery** [comment]
This is currently out of scope of pychromecast.

**Comment by interfect** [comment]
I worked out how to do this with `curl` after fome more research. It breaks down into calls to:

1. Scan wifi networks
2. Connect to a wifi network with password encrypted to the Chromecast's public key
3. Save wifi connection details
4. Also maybe set the Chromecast's name

Maybe some of those individual operations might be in scope? Maybe someone wants their Chromecast to be renamed or dump on different wifis on a schedule or something?
