### ISSUE TITLE
Chromecast by IP

### ISSUE THREAD

**Issue by jose-hamilton-mota** [home-assistant-libs/pychromecast#577]
before upgrading to newer version, i was able to connect a chromecast directly over IP :
`cast = pychromecast.Chromecast('192.168.1.10')`
but now returns the error: 
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pychromecast/__init__.py", line 271, in __init__
    if not cast_info.cast_type:
AttributeError: 'str' object has no attribute 'cast_type'
`
Is there any method in this new version to do this, without having to scan the entire network?

**Comment by emontnemery** [comment]
Checkout `get_chromecast_from_host`:
```py
    port = port or 8009
    services = [ServiceInfo(SERVICE_TYPE_HOST, (ip_address, port))]
    cast_info = CastInfo(
        services, uuid, model_name, friendly_name, ip_address, port, None, None
    )
    return Chromecast(
        cast_info=cast_info,
        tries=tries,
        timeout=timeout,
        retry_wait=retry_wait,
    )
```
