### ISSUE TITLE
'Chromecast' object has no attribute 'device'

### ISSUE THREAD

**Issue by xihajun** [home-assistant-libs/pychromecast#578]
Hello, I have a google nest hub and nest mini, but when I try to print device info, it shows `'Chromecast' object has no attribute 'device'`
```
>>> print(cast.device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Chromecast' object has no attribute 'device'
```

Do you think I have to buy a Chromecast to make it working?

**Comment by xihajun** [comment]
it works fine, but just there is no device attribute any more?

**Comment by emontnemery** [comment]
It was removed in https://github.com/home-assistant-libs/pychromecast/pull/556, you can print `cast.cast_info` for similar information

**Comment by xihajun** [comment]
> It was removed in #556, you can print `cast.cast_info` for similar information

Thanks a million! May I kindly ask if this package could do things reversely, like embed some apps into the home and use the home to send messages? 

Many thanks

**Comment by emontnemery** [comment]
> May I kindly ask if this package could do things reversely, like embed some apps into the home and use the home to send messages to the server or cloud

This library can help you start and control an app on a Google Home device, but it won't help you actually create your own app.
You can maybe study the Home Assistant app: https://github.com/home-assistant/frontend/tree/dev/cast if you want to make your own app

Try the demo here: https://cast.home-assistant.io/
(The Home Assistant app requires a Google Home device with a screen, it doesn't work on audio-only devices)

**Comment by xihajun** [comment]
> > May I kindly ask if this package could do things reversely, like embed some apps into the home and use the home to send messages to the server or cloud
> 
> This library can help you start and control an app on a Google Home device, but it won't help you actually create your own app. You can maybe study the Home Assistant app: https://github.com/home-assistant/frontend/tree/dev/cast if you want to make your own app
> 
> Try the demo here: https://cast.home-assistant.io/ (The Home Assistant app requires a Google Home device with a screen, it doesn't work on audio-only devices)

Thanks so much! That's really helpful

**Comment by jhfoo** [comment]
Can the example in the landing page be updated to reflect the changes? These are the lines that need updating:

```
>> print(cast.device)
DeviceStatus(friendly_name='Living Room', model_name='Chromecast', manufacturer='Google Inc.', uuid=UUID('df6944da-f016-4cb8-97d0-3da2ccaa380b'), cast_type='cast')
```

**Comment by tkalfaoglu** [comment]
> Can the example in the landing page be updated to reflect the changes? These are the lines that need updating:
> 
> ```
> >> print(cast.device)
> DeviceStatus(friendly_name='Living Room', model_name='Chromecast', manufacturer='Google Inc.', uuid=UUID('df6944da-f016-4cb8-97d0-3da2ccaa380b'), cast_type='cast')
> ```

Yes please!
