### ISSUE TITLE
No longer possible to direct connect via IP address alone?

### ISSUE THREAD

**Issue by BrizzzUK** [home-assistant-libs/pychromecast#588]
I'd like to connect directly to a chromecast device via IP address (not using discovery). However, this (very simple) code below fails with an error:

import pychromecast
cast = pychromecast.Chromecast('192.168.22.165')

The error returned is:
File "/home/dev/.local/lib/python3.9/site-packages/pychromecast/__init__.py", line 271, in __init__
    if not cast_info.cast_type:
AttributeError: 'str' object has no attribute 'cast_type'

Is this a bug or has the functionality been removed or replaced?

**Comment by emontnemery** [comment]
Please see this issue: https://github.com/home-assistant-libs/pychromecast/issues/577
