### ISSUE TITLE
1st gen chromecasts not detected on network

### ISSUE THREAD

**Issue by soreau** [home-assistant-libs/pychromecast#692]
I have two 1st gen chromecasts, and apparently the firmware was changed a few months ago in a way that prevents pychromecast (13.0.4) from discovering either devices. Trying basic tests found in the README, they fail to find any device. Mobile devices can find the chromecasts using the google home app, but since the fw change, it takes longer to discover than it did before, in many cases. `avahi-browse -a` doesn't show the chromecasts but `avahi-browse _googlecast._tcp` does.

**Comment by howff** [comment]
Have you tried all three of https://github.com/home-assistant-libs/pychromecast/blob/master/examples/discovery_example.py and https://github.com/home-assistant-libs/pychromecast/blob/master/examples/discovery_example2.py and https://github.com/home-assistant-libs/pychromecast/blob/master/examples/discovery_example3.py ?

The basic `discovery_example.py` doesn't work for me, but `discovery_example2.py` does work (slowly).

**Comment by soreau** [comment]
@howff Thanks for pointing these out. The first one is the only one that works for me, and it is intermittent. Sometimes it finds both immediately, other times it only finds one and not the other (even after waiting several minutes), and sometimes nothing at all.

**Comment by soreau** [comment]
After upgrading the router, all things wifi on the LAN are drastically improved. `avahi-browse -a` shows the chromecasts, and the pychromecast examples work pretty speedily. @howff Thanks for your help, closing for now.
